version: 2

defaults: &defaults
  working_directory: /go/src/github.com/weaveworks/Watch
  docker:
    - image: circleci/golang:latest

jobs:
  tests:
    <<: *defaults
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: ./gok.sh


  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: go build
      - run: docker build -t docker.io/weaveworks/watch -t docker.io/weaveworks/watch:$(./image-tag) .
      - deploy:
          name: push image
          command: |
            if [ -z "${CIRCLE_TAG}" -a "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" docker.io
              docker push "docker.io/weaveworks/watch:$(./image-tag)"
              docker push "docker.io/weaveworks/watch"
            fi


workflows:
  version: 2
  build_deploy:
    jobs:
      - tests
      - build
